image: ubuntu:20.04

before_script:
- export INGESTUM_WORKER=multiprocessed
- export DEBIAN_FRONTEND=noninteractive
- export NLTK_DATA=~/.nltk_data
- apt-get update
- apt-get install -y --no-install-recommends wget build-essential git python3-pip python3-dev python3-virtualenv poppler-utils sox attr ffmpeg libsm-dev libxrender-dev libxext-dev libxss-dev libgtk-3-dev ghostscript tesseract-ocr
- apt-get install -y libreoffice
- apt-get install -y unzip
- mkdir ~/.deepspeech
- mkdir -p $NLTK_DATA/corpora
- wget -O $NLTK_DATA/words.zip https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/words.zip
- unzip $NLTK_DATA/words.zip -d $NLTK_DATA/corpora
- wget -O ~/.deepspeech/models.pbmm https://github.com/mozilla/DeepSpeech/releases/download/v0.7.3/deepspeech-0.7.3-models.pbmm
- wget -O ~/.deepspeech/models.scorer https://github.com/mozilla/DeepSpeech/releases/download/v0.7.3/deepspeech-0.7.3-models.scorer

tests:
  stage: test
  script:
  - ./qa.sh
  - pip install -r docs/requirements.txt
  - sphinx-build -b html docs public
  only:
  - branches
  except:
  - master

pages:
  stage: deploy
  script:
  - pip install -r docs/requirements.txt
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  only:
  - master
