#!/usr/bin/python3
#
# Copyright (c) 2020 Sorcero, Inc.
#
# This file is part of Sorcero's Language Intelligence platform
# (see https://www.sorcero.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

import json
import argparse



def dump(document):
    _type = document.get("type") if type(document) is dict else None

    if _type == "collection":
        for document in document["content"]:
            dump(document["content"])
    elif _type is not None:
        dump(document["content"])
    elif type(document) is str:
        print(document)
    else:
        print(json.dumps(document, indent=4, sort_keys=True, ensure_ascii=False))


def inspect(path):
    with open(path, "r") as file:
        document = json.load(file)
    dump(document)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("document")
    args = parser.parse_args()
    inspect(args.document)


if __name__ == "__main__":
    main()
