#!/usr/bin/python3
#
# Copyright (c) 2022 Sorcero, Inc.
#
# This file is part of Sorcero's Language Intelligence platform
# (see https://www.sorcero.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

import os
import sys
import argparse
import subprocess

PLUGINS_DEFAULT_DIR = os.path.join(os.path.expanduser("~"), ".ingestum", "plugins")


def get_default_plugins():
    plugins = os.environ.get("INGESTUM_PLUGINS_DIR", None)

    if plugins is not None:
        return plugins.split(":")

    return [PLUGINS_DEFAULT_DIR]


def install_plugin(requirements):
    print(f"Installing {requirements}")
    if not os.path.exists(requirements):
        return

    args = [sys.executable, "-m", "pip", "install", "-r", requirements]
    subprocess.check_call(args)


def install_directories(directories):
    for directory in directories:
        for plugin in os.listdir(directory):
            requirements = os.path.join(directory, plugin, "requirements.txt")
            install_plugin(requirements)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--directories",
        type=str,
        nargs="+",
        default=get_default_plugins(),
    )
    args = parser.parse_args()
    install_directories(args.directories)


if __name__ == "__main__":
    main()
