#!/usr/bin/python3
#
# Copyright (c) 2021 Sorcero, Inc.
#
# This file is part of Sorcero's Language Intelligence platform
# (see https://www.sorcero.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

import argparse

from ingestum import sources
from ingestum import transformers
from ingestum.utils import write_document_to_path


def migrate(paths):
    for path in paths:
        source = sources.Document(path=path)
        document = transformers.DocumentSourceCreateDocument().transform(source)
        write_document_to_path(document, path)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("documents", nargs="+")
    args = parser.parse_args()
    migrate(args.documents)


if __name__ == "__main__":
    main()
