#!/usr/bin/python3
#
# Copyright (c) 2021 Sorcero, Inc.
#
# This file is part of Sorcero's Language Intelligence platform
# (see https://www.sorcero.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

import json
import argparse

from ingestum import documents
from ingestum import transformers


def merge(paths, output):
    for index, path in enumerate(paths):
        if index == 0:
            collection = documents.Collection.parse_file(path)
        else:
            _collection = documents.Collection.parse_file(path)

            collection = transformers.CollectionDocumentMerge().transform(
                collection,
                _collection,
            )

    with open(output, "w") as file:
        file.write(json.dumps(collection.dict(), indent=4, sort_keys=True))
    print(f"Merged document saved as {output}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("documents", nargs="+")
    parser.add_argument("--output", type=str, default="merged.json")
    args = parser.parse_args()
    merge(args.documents, args.output)


if __name__ == "__main__":
    main()
